### ISSUE TITLE
Modelagem

### ISSUE THREAD

**Issue by lgnsparda** [Dinamica-dos-Fluidos-CFD/IsaacMouraAlencar_170059171_ReporLaboratorio#2]
- Tem muita coisa misturada no item "requisitos". Sugere-se observar o repositório de informações para fazer o relato do trabalho.
- Refazer completamente a parte da modelagem

**Comment by isaacalencar** [comment]
dei uma alterada e adicionei algumas coisas

**Comment by lgnsparda** [comment]
- Nenhum ponto colocado acima foi corrigido.
**_- O trabalho deve recomeçar do zero._**

**Comment by isaacalencar** [comment]
refiz professor.

**Comment by lgnsparda** [comment]
- O readme está bastante incompleto e as perguntas no repositório de informações **não estão respondidas!**
- **A escrita passa a impressão de que este trabalho e esta etapa não estão sendo levadas a sério!**
- As seguintes perguntas **devem ser respondidas**:
- Qual é o objetivo do projeto?
- Quais são seus requisitos de solução?
- Qual é a finalidade do projeto?
- Que hipóteses de simplificação podem ser adotadas?
- Que hipóteses de simplificação devem ser adotadas?
- Qual é a precisão requerida nos resultados do projeto?
- Qual é o prazo de entrega do projeto?
- Há outra metodologia mais adequada do que CFD?

**Comment by isaacalencar** [comment]
Perdao professor, eu estava um pouco perdido nesta parte, coloquei essas perguntas e suas respostas na parte de requisitos.

**Comment by lgnsparda** [comment]
- O que você está chamando de "requisitos" é a modelagem do problema! Qual é o motivo desta nomenclatura?

**Comment by isaacalencar** [comment]
pensei em requisitos como requisitos da modelagem/simulação, vou alterar aqui e retirar essa nomenclatura entao.

**Comment by isaacalencar** [comment]
mais alguma alteração a ser feita professor?

**Comment by lgnsparda** [comment]
- A resposta da finalidade está ruim! Este trabalho é de engenharia ou acadêmico?
- Onde estão os requisitos de solução?
- A resposta da precisão requerida está errada!
- Melhorar a formatação, buscar fazer este relatório com mais esmero!

**Comment by isaacalencar** [comment]
fiz algumas alterações professor.

**Comment by lgnsparda** [comment]
- Porque o tópico se chama "pré-processamento e modelagem"? São duas coisas distintas!
- Os requisitos de solução estão incorretos. Responda o seguinte: O que é requisitado de sua simulação? O que ela deve entregar?
- Melhorar a resposta da pergunta "Há outra metodologia mais adequada do que CFD?"
- O prazo final é no dia 04/12. Porque colocou um dia depois do prazo?

**Comment by isaacalencar** [comment]
fiz algumas alteraçoes novamente professor.

**Comment by isaacalencar** [comment]
Já comecei também a próxima etapa já que o tempo esta acabando.

**Comment by lgnsparda** [comment]
- O tópico 1 **Não é Pré-processamento**, é modelagem!
- Os requisitos de solução ainda estão errados. O que é requisitado de sua solução não são confirmações, mas sim resultados!
- Não colocar informações de geometria e malha ainda, a parte 1 ainda está fraca!
- O que está no seu repositório passa a impressão de que você está sem rumo em seu trabalho. Siga o que o repositório de informações coloca **à risca**!

**Comment by isaacalencar** [comment]
por resultados, seria resultados referentes a vazão e pressao na entrada e saida?ou algum outro valor?

**Comment by lgnsparda** [comment]
- O texto do requisito de solução ainda pode melhorar. Sugere-se a seguinte redação:
"O requisito de solução do Projeto de CFD é a vazão e pressão no interior da instalação mencionada. Com estes valores, será executado um estudo paramétrico de modo a avaliar se estes resultados são suficientes para atender os objetivos."
- A redação está muito desleixada, com faltas de acentuação e frases longas. Ter mais rigor na escrita do texto!

**Comment by isaacalencar** [comment]
acabou que esqueci de comentar apos fazer as alteraçoes, alterei algumas coisas, ha algum outro "paragrafo" que o senhor acha que precisa de mais um pouco de trabalho?tentei dar uma repaginada em alguns

**Comment by lgnsparda** [comment]
- Seguir para a etapa de pré-processamento

**Comment by isaacalencar** [comment]
Fiz algumas adiçoes, desta vez segui o passo a passo do arquivo de informaçoes,  estou com uma duvida na parte de Descrição do pré-processamento feito no ANSYS. seria descrever passo a passo o que eu fiz na etapa de Setup do workbench?
