### ISSUE TITLE
Pré-processamento

### ISSUE THREAD

**Issue by lgnsparda** [Dinamica-dos-Fluidos-CFD/IsaacMouraAlencar_170059171_ReporLaboratorio#3]
- Melhorar o texto como um todo. Há muitas frases sem sentido!
- A pergunta "Que escolhas devem ser feitas em relação ao processamento da solução?" não está respondida!

**Comment by isaacalencar** [comment]
fiz algumas alteraçoes aqui

**Comment by lgnsparda** [comment]
- Descrever no texto as escolhas feitas no pré-processamento.

**Comment by isaacalencar** [comment]
seria na parte do Descrição do pré-processamento feito no ANSYS ou em algum paragrafo anterior?

**Comment by lgnsparda** [comment]
- Inserir um texto descrevendo as escolhas em cada figura nas figuras do CFX-Pre. Evitar o hábito de deixar figuras sem texto.

**Comment by isaacalencar** [comment]
coloquei descrição nas imagens que estavam sem, ja que o processo e o mesmo so coloquei imagens com as condições de entrada e saída com vazão mássica devo colocar das outras condições que vou usar(pressão e velocidade)?

**Comment by lgnsparda** [comment]
- Seguir para a etapa de Processamento e Pós-Processamento
