### ISSUE TITLE
Processamento e pós processamento

### ISSUE THREAD

**Issue by lgnsparda** [Dinamica-dos-Fluidos-CFD/IsaacMouraAlencar_170059171_ReporLaboratorio#4]
- Não se observou uma análise da física do escoamento nem dos gráficos! Inserir estas análises!
- Que resultados qualitativos foram obtidos?
- A resposta da pergunta "Os resultados estão de acordo com a realidade física do escoamento?" não faz sentido. Qual referência você usou para comparar seus resultados?

**Comment by isaacalencar** [comment]
Fiz algumas alteraçoes professor.

**Comment by lgnsparda** [comment]
- Melhorar a análise das figuras, está muito pobre!

**Comment by isaacalencar** [comment]
Fiz aqui mais algumas alteraçoes;

**Comment by lgnsparda** [comment]
- Inserir o estudo paramétrico

**Comment by isaacalencar** [comment]
Inseri os resultados do estudo paramétrico no formato de uma tabela professor, não sei se podia fazer isso, fiz dessa maneira pois acho que se colocasse o passo a passo como fiz anteriormente além de ficar redundante iria quase quadruplicar o tamanho do trabalho escrito.

**Comment by lgnsparda** [comment]
- Inserir as conclusões
- Colocar o trabalho em formato de artigo científico
- Colocar o trabalho em formato de relatório técnico

**Comment by isaacalencar** [comment]
inseri as conclusões, tive alguns problemas com meu computador e so consegui colocar no formato de relatório, já fiz o upload do mesmo para o github professor.

**Comment by lgnsparda** [comment]
- Sugere-se inserir resumo e palavras chave no artigo.
- Colocar o trabalho em formato de relatório técnico

**Comment by isaacalencar** [comment]
Inseri resumo e palavras chaves, arrumei as imagens e coloquei o relatorio professor, muito obrigado.
